#!/usr/bin/env bash
# Update package list and install nginx

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
