#!/usr/bin/env bash
# Update package list and install nginx

apt -y update
apt -y upgrade
apt -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
