#!/usr/bin/env bash
# Update package list and install nginx

apt-get -y update
apt-get -y upgrade
apt-get install -y nginx


mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo 'Hello World!' > /etc/nginx/html/index.html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

	location / {
		try_files \$uri \$uri/ =404;
	}

	error_page 404 /404.html;
	location = /404.html {
		root /var/www/html;
		internal;
	}
}" > /etc/nginx/sites-ready/default
	
service nginx restart
