#!/usr/bin/env bash
# This script configures a brand new Ubuntu machine.

myhost=$(hostname)
str1="error_page 404 \/custom_404.html;\n location \/redirect_me {\n return 301 \$scheme:\/\/www.google.com;"
str2="server {\n\tadd_header X-Served-By $myhost;"

apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /usr/share/nginx/html/index.html
mkdir -p /myhost/www/html
echo "Ceci n'est pas une page" > /myhost/www/html/custom_404.html
sudo sed -i -E "s/^[^#]+location \/ \{/$str1/" /etc/nginx/sites-available/default
sudo sed -i -E "s/^server \{/$str2/" /etc/nginx/sites-available/default
sudo service nginx start
