#!/usr/bin/env bash
# displays the content of the file /etc/passwd.
# Function to display file content
display_file_content() {
    local file="$1"
    
    while IFS= read -r line
    do
        echo "$line" | cut -d ':' -f 1,3,6
    done < "$file"
}

# Main script
file="/etc/passwd"
display_file_content "$file"
