#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
hour=0
min=1
while [ $hour -lt 12 ] || { [ $hour -eq 12 ] && [ $min -le 59 ]; }; do
   echo "Hour: $hour"
   echo $min
   ((min++))
   if [ $min -eq 60 ]; then
	((hour++))
	min=0
   fi
done
