#!/usr/bin/env bash
# displays: The content of the current directory
# In a list format
# Where only the part of the name after the first dash is
# displayed (refer to the example)
for file in *; do
   if [[ -f "$file" && ! "$file" == .* ]]; then
       filename=$(echo "$file" | cut -d '-' -f 2)
       echo "$filename"
   fi
done
